### ISSUE TITLE
spafit example of cryptography and Qt

### ISSUE THREAD

**Issue by jayvdb** [indygreg/PyOxidizer#153]
https://github.com/jamesabel/spafit is an old fairly simple test case using cryptography and Qt.

I've been doing an update, many years later at https://github.com/jamesabel/spafit/pull/2

cx_Freeze is now working.

PyOxidizer is not.

I tried
```toml
[[packaging_rule]]
type = "package-root"
path = "../venv"
packages = ["PyQt5.QtWidgets"]
```

The error I get is
```py
Traceback (most recent call last):
  File "importlib.util", line 94, in find_spec
  File "main", line 4, in <module>
ModuleNotFoundError: No module named 'PyQt5.QtWidgets'
```

https://github.com/indygreg/PyOxidizer/issues/27 has a few examples, and mentions Qt5, but I didnt see a working example.
