### ISSUE TITLE
confusing comment in generated config file

### ISSUE THREAD

**Issue by dmerejkowsky** [indygreg/PyOxidizer#29]
around line 34, a comment says:

```toml
[[packaging_rule]]
type = "stdlib-extensions-policy"
...

# Only package the minimal set of extension modules needed to initialize
# a Python interpreter. Many things like won't work with this setting.
# policy = "minimal"
```

> Many things like won't work

I think the sentence is missing some words
