### ISSUE TITLE
error: unable to find PyOxidizer config file at .

### ISSUE THREAD

**Issue by justinTM** [indygreg/PyOxidizer#742]
```toml
# ./pyoxidizer.toml
[application]
name = "sniff"
version = "0.3.0"

[[binaries]]
name = "sniff"
path = "sniff/cli/sniff.py"
```

```console
$ pyoxidizer build
error: unable to find PyOxidizer config file at .
```
