### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by kshcherban** [indygreg/PyOxidizer#8]
Tried to compile [my project](https://github.com/kshcherban/acme-nginx/).
Here's `PYOXIDIZER_CONFIG`
```toml
[python_distribution]
local_path = "/opt/Downloads/cpython-3.7.1-linux64-20181218T1905.tar.zst"
sha256 = "b718a191ae79a4450e081aed9b4a92b3230465752a119035c3df98a714513a5a"

[python_config]
program_name = "acme-runner"

[python_packaging]
module_paths = ["/opt/acme-nginx/venv/lib/python3.7/site-packages"]
```

pyembed failed to compile
```
root@8d3475ae6b05:/opt/Downloads/PyOxidizer# PYOXIDIZER_CONFIG=/opt/acme-nginx/config.rst cargo build
   Compiling zstd-sys v1.4.6+zstd.1.3.7
   Compiling zstd-safe v1.4.6+zstd.1.3.7
   Compiling zstd v0.4.21+zstd.1.3.7
   Compiling pyrepackager v0.0.1 (/opt/Downloads/PyOxidizer/pyrepackager)
   Compiling pyembed v0.1.0 (/opt/Downloads/PyOxidizer/pyembed)
error: failed to run custom build command for `pyembed v0.1.0 (/opt/Downloads/PyOxidizer/pyembed)`
process didn't exit successfully: `/opt/Downloads/PyOxidizer/target/debug/build/pyembed-9e26b74a01d6372e/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-env-changed=PYOXIDIZER_CONFIG
cargo:rerun-if-changed=/opt/acme-nginx/config.rst
cargo:rerun-if-changed=/opt/Downloads/cpython-3.7.1-linux64-20181218T1905.tar.zst

--- stderr
thread 'main' panicked at 'failed to read PYTHON.json: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Rust: 1.32.0 - `cargo 1.32.0 (8610973aa 2019-01-02)`
Python installed locally: `3.7.2`
